docs/guides/features/headpose.md
static/img/headpose/a.jpeg
static/img/headpose/b.jpeg
static/img/headpose/c.jpeg
static/img/headpose/d.jpeg
static/img/headpose/e.jpeg
static/img/headpose/f.jpeg
static/img/headpose/g.jpeg
static/img/headpose/h.jpeg
static/img/headpose/i.jpeg
static/img/headpose/j.jpeg

First iteration of guide covering headpose function, ideal environment and troubleshooting tips for headpose loss.

Headpose guide

---

docs/guides/unity/soundfield-audio/soundfield-components.md
docs/guides/unity/soundfield-audio/soundfield-plugin.md
static/img/unity/enable_acoustic_map.png
static/img/unity/ml-debug-info.png
static/img/unity/ml_listener_auto.png
static/img/unity/msa_scriptable_object.png
static/img/unity/soundfield-path.jpg

Update instructions and images for the most recent changes in the Unity Soundfield plugin

Soundfield update 

---

docs/guides/device/hardware-specs.md

Create new Hardware Overview guide to replace old ML2 overview page hardware information.

Hardware Specs guide

---

docs/guides/developer-tools/android-debug-bridge/adb-bugreport.md
docs/guides/developer-tools/android-debug-bridge/android-capture-commands.md
static/img/developer-tools/adb/adb-bugreport-files.png

This page is mainly for external linking, such as [the Forums](https://forum.magicleap.cloud/).
This will make it easy for developers to submit full logs to us for debugging.

ADB Bugreport

---

docs/guides/unity/display/unity-segmented-dimming.md

- Add note for dimming objects at-runtime
- Add Simple Usecase
- Change verbiage for "old" way
- Add Advanced Usecase
- Remove API refs and old information about outdated SDK versions

Update SegmentedDimming documentation for February release

---

docs/releases/release-2022-december/os-release-notes/os-release-notes.md
docs/releases/release-2022-november/os-release-notes/os-release-notes.md
docs/releases/release-2023-february/os-release-notes/os-release-notes.md
docs/releases/release-2023-february/unity-sdk-release-notes.md
docs/releases/release-2023-january/os-release-notes/os-release-notes.md

* Add known issue to February's Unity SDK Release Notes
* Remove duplicate flash instructions from Release Notes

Release notes update

---

docs/guides/third-party/ptc/vuforia-overview.md

Add link to sample content for Vuforia Engine

---

docs/guides/developer-tools/ml-hub/ml-hub-advanced-capture.md
static/img/ml-hub/advanced-capture/advanced_capture_home.jpg
static/img/ml-hub/advanced-capture/capture_path.jpg
static/img/ml-hub/advanced-capture/capture_success.jpg
static/img/ml-hub/advanced-capture/composition_settings.jpg
static/img/ml-hub/advanced-capture/home_no_preview.jpg
static/img/ml-hub/advanced-capture/home_preview.jpg
static/img/ml-hub/advanced-capture/image_settings.jpg
static/img/ml-hub/advanced-capture/video_settings.jpg

Initial guide describing the Advanced Capture module in Magic Leap Hub. 
Preview:

Advanced Capture documentation

---

docs/guides/unity/input/voice-intents/configure-voice-intents.md
docs/guides/unity/input/voice-intents/start-and-stop-input.md
docs/guides/unity/input/voice-intents/voice-input-system-settings.md
docs/guides/unity/input/voice-intents/voice-intents-api-overview.md
docs/guides/unity/input/voice-intents/voice-intents-example-scripts.md
docs/guides/unity/input/voice-intents/voice-intents-overview.md
docs/guides/unity/input/voice-intents/voice-slots.md
static/img/unity/SimpleSlot.png
static/img/unity/SlotsOr.png

 Add Voice Slots documentation and reorder section articles

---

docs/guides/arcloud/on_prem.md

Changes:
* correct path to istio.yaml
* add more details about Docker integration with WSL distributions
* update link texts

Fix AR Cloud Windows docs

---

docs/guides/unity/getting-started/configure-unity-settings.md
static/img/unity/setup/setup-tool-import.jpg
static/img/unity/setup/setup-tool-package-manager.jpg
static/img/unity/setup/setup-tool-window.jpg

Add Magic Leap Setup Tool instructions to Getting Started guide

---

docs/guides/unity/getting-started/configure-unity-settings.md

We don't currently have information about Scoped Registry addition/alteration. Now, we can:

Add information about adding Scoped Registries to the Package Manager

---

.gitattributes
docs/guides/developer-tools/app-sim/app-simulator.md
package-lock.json
package.json
static/videos/AppSimOverview_V2_2.mp4
yarn.lock

* Add App Sim overview video to Application Simulator page in Developer Documentation.

Add Application Simulator video

---

docs/guides/arcloud/on_prem.md
docs/guides/arcloud/ova.md

Change in the AR Cloud docs:
* fix command to update istio.yaml for on-prem Windows deployments
* update information about detecting and enabling virtualization for VirtualBox on Windows
* describe runtime environments for the VM images

Update ARCloud docs

---

docs/guides/arcloud/_virtual_box_import.md
docs/guides/arcloud/ova.md
versioned_docs/version-22-Feb-2023/guides/arcloud/_virtual_box_import.md

Minor changes to fix the spelling and phrasing on AR Cloud documentation.

Updated wording on AR Cloud docs

---

docs/guides/unity/soundfield-audio/soundfield-components.md
static/img/unity/msa_mixer_meter.png

Add new MSA audio component documentation

---

docusaurus.config.js

*Fix broken link from original Unity Getting Started link

Add Unity Getting Started redirect

---

docs/guides/developer-tools/ml-hub/error-reporting.md
docs/guides/native/getting-started/command-line-workflow.md

Remove remaining references to The Lab 2.0

---

docs/guides/remote-rendering/_category_.json
docs/guides/remote-rendering/remote-rendering-service.md
docs/guides/remote-rendering/remote-rendering.md
docs/releases/release-2023-april/sdk-release-notes.md
static/img/remote-rendering/client-apk.png
static/img/remote-rendering/remote-rendering-ml-hub-tile.png

* Update steps to access Remote Rendering from Magic Leap Hub
* Add instructions to prevent audio loopback noise when combined with Device Stream

Update Remote Render documentation

---

docusaurus.config.js

* Add redirect to Remote Rendering Set up guide

Add Remote Rendering redirect

---

docs/guides/unity/perception/anchors/spatial-anchors-example.md
docs/guides/unity/resources/spatial-anchors-example-project.md
docs/guides/unity/resources/virtual-keyboard.md

Add references to Spatial Anchors example project on GitHub

---

docs/guides/remote-render/unreal-engine-5.md

Improve messaging behind possible input issues.

Update notice regarding Controller input issues

---

docs/guides/developer-tools/app-sim/app-simulator.md
package.json
static/videos/AppSimOverview_V2_2.mp4
yarn.lock

- Replace checked-in .mp4 with unlisted YouTube video

Add YouTube Player, Replace Checked-In .mp4 Video

---

package.json
yarn.lock

This is a maintenance PR to make sure we don't get too far behind in the versions

Upgrade Docusaurus to 2.4.0

---

docs/guides/developer-tools/app-sim/app-sim-action-bindings.md
static/img/app-sim/edit-bindings-dropdown.jpg
static/img/app-sim/edit-bindings-dropdown.png
versioned_docs/version-22-Mar-2023/guides/developer-tools/app-sim/app-sim-action-bindings.md

Replace old ZI action bindings screenshot with new AppSim screenshot

---

docs/guides/unity/getting-started/install-the-tools.md

Some plugins may require additional dependencies that are undocumented.

Add Visual Studio missing workload error message

---

docs/guides/developer-tools/app-sim/app-sim-unity.md
docs/guides/unity/app-simulator/_app-sim-unity-mlhub.md
docs/guides/unity/app-simulator/app-sim-unity-zif.md
static/img/app-sim/app-sim-load-default-layout.png
static/img/app-sim/app-sim-play-buttons.png
versioned_docs/version-22-Mar-2023/guides/unity/app-simulator/_app-sim-unity-mlhub.md

- Remove misleading App Sim for ML Hub page
- Encourage App Sim for Unity workflow
- Add relevant screenshots and instructions to disambiguate steps in setup and execution

Add App Sim for Unity improvements

---

docs/guides/unity/getting-started/configure-unity-settings.md
docs/guides/unity/getting-started/create-a-project.md
docs/guides/unity/getting-started/graphics-settings.md
docs/guides/unity/getting-started/install-the-tools.md
docs/guides/unity/sdk-example-scenes/sdk-install-setup.md

Update Untiy version to omit ambiguous alpha and beta 2022.3 and up

---

docs/guides/arcloud/_virtual_box_import.md
docs/guides/arcloud/ova.md

```python
>>> Explicit is better than implicit
```

Add instructions for downloading OVA image using auth

---

docs/guides/arcloud/_env_file.md
docs/guides/arcloud/_install_istio_aws.md
docs/guides/arcloud/aws.md
docs/guides/arcloud/gcp.md
docs/guides/arcloud/on_prem.md

Changes:
* add service annotation to support the breaking changes introduces by AWS LB controller
* add env files to store the configuration
* describe using Global Accelerator
* provide information about using IP addresses only

Update AWS docs

---

docs/releases/release-2023-may/os-release-notes/os-release-notes.md

* Update build number for May release

Update May Release Notes

---

docs/guides/native/native-openxr-setup.md
docs/releases/release-2023-may/unity-sdk-release-notes.md

* Add supported OpenXR extensions
* Updated minimum OpenXR version to 1.0.27

Update OpenXR documentation

---

docs/api-ref/api/Modules/group___camera/struct_m_l_depth_camera_data.md

* Update text to reflect API is experimental

Update MLDepthCameraData API

---

docs/api-ref/api/Modules/group___camera/struct_m_l_depth_camera_data.md

Reverts magicleap/developer-portal-docs#137

Revert "Update MLDepthCameraData API"

---

docs/guides/unity/resources/virtual-keyboard.md

* Replace old documentation with current Magic Leap XR Keyboard documentation

Update Magic Leap XR Keyboard documentation

---

docs/guides/unity/resources/virtual-keyboard.md

* Correct Magic Leap Software License Agreement link

Update Magic Leap XR Keyboard documentation link

---

docs-versions.json

Add current date for planned June release

---

docs/guides/third-party/agora/_category_.json
docs/guides/third-party/agora/agora.md
docs/guides/third-party/ptc/_category_.json
yarn.lock

* Add guide to build live video streaming into AR app on Magic Leap 2

Add Agora live video streaming guide

---

docs/releases/release-2023-june/os-release-notes/os-release-notes.md

- Fix incorrect OS version number

Update June Release Notes

---

docs/guides/features/android-intents-overview.md
docs/guides/features/audio.md
docs/guides/features/bluetooth-input.md
docs/guides/features/controller-features.md
docs/guides/features/dimmer-feature/_category_.json
docs/guides/features/eye-tracking/_category_.json
docs/guides/features/headpose.md
static/img/audio/default.png
static/img/audio/frequency.png

* Add audio guidelines to developer documentation

Add audio guide

---

docs/guides/third-party/networking/photon-fusion.md
docs/guides/third-party/visometry/_category_.json
docs/guides/third-party/visometry/visionlib.md
static/img/third-party/agora.jpeg
static/img/third-party/visionlib.jpeg

Add Visionlib SDK tutorial to third-party tools section

Update third-party tools section

---

docs/guides/third-party/agora/agora.md
docs/guides/third-party/ptc/_category_.json
docs/guides/third-party/visometry/_category_.json

* Update third party integration titles

Update third-party page titles

---

docs/guides/third-party/agora/agora.md
docs/guides/third-party/ptc/_category_.json
docs/guides/third-party/third-party-resources.md
docs/guides/third-party/visometry/_category_.json
static/img/third-party/agora.png
static/img/third-party/photon.png
static/img/third-party/visionlib.png
static/img/third-party/visometry.png

* Redesign landing page to include images of third-party resources.

Refactor Third Party Resources Landing Page

---

docs/guides/third-party/third-party-resources.md

Update third-party resources links

---

docs/guides/features/webxr-viewer.md

Push new WebXR content to branch.

Updated WebXR Viewer file to reflect new changes

---

docs/guides/features/voice-commands/voice-intents-developer-toolkit.md
static/img/vidtk/vidtk-1.png
static/img/vidtk/vidtk-10.png
static/img/vidtk/vidtk-11.png
static/img/vidtk/vidtk-12.png
static/img/vidtk/vidtk-13.png
static/img/vidtk/vidtk-2.png
static/img/vidtk/vidtk-3.png
static/img/vidtk/vidtk-4.png
static/img/vidtk/vidtk-5.png
static/img/vidtk/vidtk-6.png
static/img/vidtk/vidtk-7.png
static/img/vidtk/vidtk-8.png
static/img/vidtk/vidtk-9.png

* Add guide supporting the Voice Intents Developer Toolkit

Feat: Add Voice Intents Developer ToolKit Guide

---

docs/guides/third-party/_category_.json

Correct Third-Party Resources page title

---

docs/guides/best-practices/privacy-security-safety.md

* Add page to outline best practices for developers to follow concerning privacy, security and safety

Add developer best practices guide for privacy

---

docs/guides/device/sleep-mode.md

* Update text to highlight effective date

Update Sleep Mode guidance

---

docs/guides/third-party/wwise/_category_.json
docs/guides/third-party/wwise/wwise-integration.md
static/img/unity/wwise/a.jpg
static/img/unity/wwise/b.jpg
static/img/unity/wwise/c.jpg
static/img/unity/wwise/d.jpg
static/img/unity/wwise/e.jpg
static/img/unity/wwise/f.jpg
static/img/unity/wwise/g.jpg
static/img/unity/wwise/h.jpg
static/img/unity/wwise/i.jpg
static/img/unity/wwise/j.jpg
static/img/unity/wwise/k.jpg
static/img/unity/wwise/l.jpg
static/img/unity/wwise/m.jpg
static/img/unity/wwise/n.jpg
static/img/unity/wwise/o.jpg
static/img/unity/wwise/p.jpg
static/img/unity/wwise/q.jpg
static/img/unity/wwise/r.jpg
static/img/unity/wwise/s.jpg
static/img/unity/wwise/t.jpg
static/img/unity/wwise/u.jpg
static/img/unity/wwise/v.jpg
static/img/unity/wwise/w.jpg
static/img/unity/wwise/x.jpg

Add Wwise Unity guide with images

---

docs/guides/features/spatial-mapping/object-occlusion.md

Object Occlusion Overview content

---

docs/guides/developer-tools/lumin-aosp-tools/renderdoc.md
static/img/developer-tools/lumin-aosp-tools/renderdoc/install_renderdoc_from_package_manager.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_choose_capture.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_debug_shader.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_disassembly_window.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_examine_pixel.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_initialization_parameters.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_open_file_capture.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_open_texture_list.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_pixel_history.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_pixel_history_panel.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_pixel_info.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_replay_context.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_texture_resource_details.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/rd_view_capture.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_capture_frame.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_capture_progressbar.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_captures_collected.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_check_server_ready.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_choose_app.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_device_attached.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_download.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_install.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_launch.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_launch_app.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_magicleap_localhost.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_open_capture.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_replay.png
static/img/developer-tools/lumin-aosp-tools/renderdoc/renderdoc_tool.png

Add RenderDoc guide

---

docusaurus.config.js

* Delete trailing slash property in config file

Remove trailing slash property

---

docs/guides/unreal/unreal-create-app.md
docs/guides/unreal/unreal-getting-started.md
docs/guides/unreal/unreal-overview.md
static/img/unreal-5/previewdocs/set-new-window-environment-variable.png
static/img/unreal-5/previewdocs/set-window-environment-variables.png

Unreal docs staging

---

docs/releases/release-2023-july/os-release-notes/os-release-notes.md

Add several bug fixes from the 1.2.1 OS to the 1.3.1 OS release notes page

Add missing release notes for 1.2.1

---

docs/guides/developer-tools/lumin-aosp-tools/radeon-gpu-profiler.md
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/draw_capture_call_breakdown.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/draw_capture_profile.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/draw_event_timing.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/draw_frame_summary.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/draw_select_profile.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_add_host_name.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_all_icon.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_check_wifi_connection.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_connection_ok.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_device_connected.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_download_screen.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_launch_from_hub.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_package_manager.png
static/img/developer-tools/lumin-aosp-tools/radeon-gpu-profiler/rgp_set_connection_local.png

Ready for commenting and review.

New RGP documentation
