magicleap/developer-portal-docs

docs/guides/device/controller-features.md, docs/guides/device/developer-mode.md, docs/guides/device/updating-the-os/_category_.json, static/img/developer-mode/about.jpg, static/img/developer-mode/buildnumber.jpg, static/img/developer-mode/settings.jpg
Short documentation with screenshots showing the user how to enable Developer Mode on OS version 1.1.0 or later.
=> Add Developer Mode guide to Device Guides

package.json, yarn.lock
In the interest of not getting too far behind, let's keep Docusaurus on the latest version (in this case, `2.3.1`).
Changelogs for the versions can be found here:
https://docusaurus.io/changelog
**After merging, make sure you `yarn install` on the next time you `git fetch upstream && git checkout upstream/main` in order for the changes to be in-effect in your environment**.
=> Upgrade Docusaurus packages to 2.3.1

docs/guides/native/native-openxr-setup.md, static/img/ml-hub/ml_hub_package_manager.png, static/img/ml-hub/ml_hub_package_manager_all.png, static/img/ml-hub/ml_hub_package_manager_native_openxr.png, static/img/ml-hub/ml_hub_package_manager_openxr.png
Add information on where to download the Open XR Examples. Using the custom image tag so additional information about the image can be shown. Using `require` to return an error if the image link ever breaks
=> Add additional information about Open XR examples

docs/guides/developer-tools/app-sim/app-sim-key-api-features.md
- The link `Show API Features...` in the Hub now points to the developer portal. All related information on the developer portal is being removed.
- The API support was updated.
=> App Sim: Removed info on cached copy and added API updates  

docs/guides/arcloud/_install_arcloud.md
Adding additional kubernetes security labels to the arcloud namespace refer to [ARCLOUD-1146](https://magicleap.atlassian.net/browse/ARCLOUD-1146)
=> docs: adding security labels to arcloud namespace instructions

docs/guides/arcloud/_deployment_verification_secure.md, docs/guides/arcloud/_install_arcloud.md, docs/guides/arcloud/_install_arcloud_setup.md, docs/guides/arcloud/_install_arcloud_setup_secure.md, docs/guides/arcloud/_register_device.md, docs/guides/arcloud/aws.md, docs/guides/arcloud/gcp.md, docs/guides/arcloud/on_prem.md
Update instructions for Google Cloud and AWS to deploy without `--no-secure` flag.
=> docs: remove no-secure flag from public cloud deployments

docs/guides/arcloud/_debian_dependencies.md, docs/guides/arcloud/on_prem.md
It has been discovered that there are some missing instructions for brand-new machines.
=> Add instructions for base dependencies for AR Cloud instructions

docs/guides/remote-rendering/_category_.json, docs/guides/remote-rendering/remote-rendering-service.md, docs/guides/remote-rendering/remote-rendering.md, static/img/remote-rendering/magic-leap-remote-rendering-installation.png, static/img/remote-rendering/remote-rendering-ml-hub-button.png, static/img/remote-rendering/remote-rendering-ml-hub-tile.png
* Add Remote Rendering setup guide to install and run the Magic Leap Remote Rendering Service through the Magic Leap Hub
=> Add Remote Rendering setup guide

docusaurus.config.js
* Add Google Tag Manager containerId to docusaurus config file to enable Google Tag Manager functionality
=> Add Google Tag Manager to Developer Portal

docs/guides/unity/debugging/unity-debugging-via-visual-studio.md
* Clarify instructions for continuing to load an application for debugging once the managed debugger from Visual Studio is connected
=> Update instructions for Unity debugging via Visual Studio

docs/guides/features/eye-tracking/eye-calibration.md, docs/guides/features/eye-tracking/eye-tracking.md, docs/guides/unity/input/eye-tracking/eye-tracking-api-overview.md, docs/guides/unity/input/eye-tracking/eye-tracking-overview.md, docs/guides/unity/input/eye-tracking/eye-tracking-porting-guide.md, docs/guides/unity/input/eye-tracking/eye-tracking-subsystem-extension.md, docs/guides/unity/input/eye-tracking/tracked-pose-driver-eye-tracking.md, docs/guides/unity/input/eye-tracking/unity-input-system-eye-tracking-input.md
* Add note to Eye Tracking API pages stipulating if an application collects, stores, transfers or otherwise uses data off the Magic Leap 2 device that is received via this API, the application must comply with the Magic Leap 2 Eye Tracking Data Transparency Policy at https://www.magicleap.com/eye-tracking.
=> Add Magic Leap transparency statement to Eye Tracking API pages

docs/guides/developer-tools/app-sim/app-simulator.md
* Remove the autoplay functionality from the video at the top of the App Sim Overview page under Developer Tools
=> Remove autoplay from App Sim video

docs/guides/remote-rendering/_category_.json
The `_category_.json` file referenced a page that did not exist.
=> Fix Remote Rendering Overview Definition

docs/releases/release-2023-april/unity-mrtk-release-notes.md
* Remove outdated instructions mentioning support of Unity SDK 1.3.0.
=> Remove outdated text from MRTK SDK Release Notes

docs/guides/remote-render/unreal-engine-5.md
This was overlooked previously.
=> Remove references to 'Windrunner' for Remote Render service

docs/guides/developer-tools/ml-hub/magic-leap-hub.md
Removed excess content that was left over by mistake.
Before:
After:
=> Remove superfluous content from ML Hub overview page

docs/guides/remote-render/unreal-engine-5.md, static/img/unreal-5/alpha-channel/content-browser-new-material.png, static/img/unreal-5/alpha-channel/enable-alpha-channel-post-processing.png, static/img/unreal-5/alpha-channel/level-post-process-volume.png, static/img/unreal-5/alpha-channel/material-graph-component-mask-one-minus.png, static/img/unreal-5/alpha-channel/material-graph-new-scene-texture.png, static/img/unreal-5/alpha-channel/material-graph-output-alpha.png, static/img/unreal-5/alpha-channel/material-graph-post-process-material-2.png, static/img/unreal-5/alpha-channel/material-graph-post-process-material.png, static/img/unreal-5/alpha-channel/post-process-volume-infinite-extent.png, static/img/unreal-5/alpha-channel/window-enable-content-browser.png
The base Unreal 5 Remote Render capabilities do not include a proper alpha channel. This is a limitation of Unreal Engine, specifically. This can be corrected with post-processing.
=> Remote Render Unreal 5 Alpha Settings

docs/guides/remote-rendering/_category_.json, docs/guides/remote-rendering/remote-rendering-service.md, docs/guides/remote-rendering/remote-rendering.md, docs/guides/remote-rendering/unreal-engine-5.md
Branding has landed on **Remote Render**.
=> Replace 'Remote Render' with Remote Rendering

docs/guides/remote-rendering/remote-rendering-service.md
With more and more questions being asked about Remote Rendering, it's time to add troubleshooting steps that allow for Magic Leap to gleen information from logs.
=> Add script execution for receiving logs from Remote Rendering service

docs/guides/device/hardware-tips.md
Add documentation to determine whether Magic Leap 2 Device is Medical or Enterprise edition.
=> Add hardware tip to determine device edition

docs/releases/release-2023-april/unity-sdk-release-notes.md
Update Release Notes for Unity 1.6.1 SDK to reflect enforcement of the minimum clipping plane to 37cm
=> Add Unity 1.6.1 Release Notes update

docs/guides/developer-tools/ml-hub/ml-hub-package-manager.md
Delete incorrect instructions about Package Manager removing previously installed versions when updating in the Hub
=> Remove inaccurate note

docs/releases/overview.md, docs/releases/release-2023-september/os-release-notes/os-release-notes.md
Add missing information on the Overview page and replace sprint naming
=> Update release notes Overview page to add September 23

docs/guides/unreal/unreal-getting-started.md
- Fixed formatting and MLSDK path
- Disambiguate where to download OpenJDK (Java developer kit website is ambiguous)
- Changed ndk to the version that will be used by Unreal
- Added note to correct SetupAndroid.bat script
=> Edits to Unreal setup guide
